
* Yin Xu
M
 5
You cause such powerful Yin Xu, $N simply dies.
$n causes such powerful Yin Xu, you simply die.
$n causes such powerful Yin Xu upon $N, $E simply dies.
$E is unharmed by your attempt to cause Yin Xu upon $M.
$n attempts to inflict Yin Xu upon you, but you manage to avoid it.
$n attempts to inflict $N with Yin Xu but fails.
A look of agony stretches across $N's face as $E is inflicted by your Yin Xu.
You clutch your guts as the agony of Yin Xu is inflicted by $n.
$N clutches $S guts as the agony of Yin Xu is inflicted by $n.
Dumbass... $N is a God...
$n tries to inflict Yin Xu upon you.  Sure.
$N gives $n a a sidelong look and a smirk.

* Yang Xu
M
 6
You cause $N's internal organs to fail completely.  $E dies.
$n causes your internal organs to fail completely.  You die.
$n causes $N's internal organs to fail completely. $N dies.
Your attempt to seize $N's internal organs fails.
$n attempts to seize your organs with Yang Xu but fails.
$n attempts to seize $N's organs with Yang Xu but fails.
$N keels over from extreme pain as $S organs experience Yang Xu.
You keel over from the extreme pain of Yang Xu inflicted by $n.
$N keels over from the extreme pain of Yang Xu inflicted by $n.
Dumbass... $N is a God...
$n tries to inflict Yang Xu upon you.  Sure.
$N gives $n a a sidelong look and a smirk.

* Psionic Drain
M
 8
You drain the last drop of life out of $N.
$n drains the last drop of life out of your body.
$n drains the last drop of life out of $N's body.
You fail to drain $N's energy.  $S Shen is too strong.
$n fails to drain your energy.  Your Shen is too strong.
$n fails to drain $N's energy.  $S Shen is too strong.
You drain $N's psionic energy.
$n drains your psionic energy.
$n drains $N's psionic energy.
You can't.
$n tries to drain your psionic energy.  Who the hell does $E think $E is?
$N thinks about bitchslapping $n.  $n deserves it.

* Psychic Fury
M
 10
Your fury was too much for $N. $E is dead!
$n begins chanting in an odd tongue as you begin screaming your death cry.
$n begins chanting in an odd tongue as $n begins screaming $s death cry.
Your focus of mental fury goes wide.
A wash of $n's mental hatred for you blows by, barely missing.
A wash of $n's mental hatred of $N barely misses $M.
Your mental fury slams directly to the core of $N's brain!
$n's mental fury slams directly to the core of your brain!
$N screams as $n's mental fury slams directly to the core of $s brain!
Get real.  You can't even think about $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n! 

$
