* Dibrova-style messages file.  The structure is identical to
* CircleMUD 3.0, with the difference being that we keep 
* separate lists for various messages.  Each list is loaded
* from it's own file.
*
* Messages for good, ol' fashioned skills.

***************************************************************************
*                           Offensive Skills                              *
***************************************************************************

* Backstab
M
 1
$N makes a strange sound but is suddenly very silent as you place $p in $S back.
Suddenly $n stabs you in the back, R.I.P....
$n places $p in the back of $N, resulting in some strange noises, a lot of blood, and a corpse.
$N quickly avoids your backstab and you nearly cut your own finger!
$n tries to backstab you, but you avoid $m!
$n tries to backstab $N but nearly cuts $s own finger!
$N makes a strange sound as you place $p in $S back!
Suddenly $n stabs you in the back!
$n places $p in the back of $N, resulting in some strange noises and some blood!
$N sends you a look that makes you forget all about backstabbing.
$n tries to backstab you, but changes $s mind.
$n tries to backstab $N, but changes $s mind.

* Bash
M
 2
$N doesn't recover from your bash! -- $E is dead.
As $n bashes at you, you give up living and die...
$N dies after $n has bashed $M!
As $N avoids your bash, you topple over and fall to the ground!
You dodge a bash from $n who loses $s balance and falls!
$N avoids being bashed by $n who loses $s balance and falls!
Your bash at $N sends $M sprawling!
$n sends you sprawling with a powerful bash!
$n sends $N sprawling with a powerful bash!
Your effort to bash $N sends YOU sprawling on the ground.
$n fruitlessly tries to bash you and is sent sprawling.
$n dares a bash at $N and is sent sprawling without touching $M.

* Kick
M
 4
Your kick at $N's kidneys made $M die.
$n kills you by kicking your kidneys in!
$N dies from $n's last kick in $S kidneys!
Your beautiful full-circle kick misses $N by a mile.
$n makes a nice balletstep which plants $s foot a mile above your head.
$n makes a nice balletstep which plants $s foot a mile above $N's head.
Your boots need polishing again -- blood all over them...
$n wipes $s boots in your face!
$n wipes $s boots in the face of $N!
$N makes you kick at a huge stone appearing from nowhere -- OUCH!
You make $n kick a huge stone appearing from nowhere -- *giggle*
$n starts kicking a huge stone which suddenly appears.
M
 4
Your kick at $N's face splits $S head open -- yummy!
$n aims a kick at your face which splits your head in two!
$n neatly kicks $N's head into pieces -- YUMMY!
You miss your kick at $N's groin, much to $S relief...
$n misses a kick at your groin, you breathe lighter now...
$n misses a kick at $N's groin, much to $N's relief...
Your kick hits $N in the solar plexus!
You're hit in solar plexus, wow, this is breathtaking!!
$n kicks $N in solar plexus, $N is rendered breathless!
You attempt to kick $N but lose your balance and fall face down in some mud that has suddenly appeared.
When $n tries to kick you, you quickly make him fall in some mud you have created.
$n falls face down in some mud created by $N.

* Deathblow 
M
 14
$N doesn't recover from your wicked deathblow! -- $E is dead.
As $n delivers a wicked deathblow, you give up living and die...
$n's wicked deathblow leaves $N dead.
$N sidesteps your deathblow.  You barely keep your balance.
You sidestep a deathblow from $n who only barely manages to keep $M feet.
$N sidesteps a deathblow by $n who barely keeps $M feet.
You CRUSH $N with a powerful deathblow!
$n CRUSHES you with a powerful deathblow!
$n CRUSHES $N with a powerful deathblow!
Your pitiful attempt is discarded with a yawn.
You easily avoid $n's deathblow attempt.
$N yawns as $M watches $n's pitiful attempt at a deathblow.
* Circle
M
 15
You circle around $N and slit $S throat.
$n circles around you and slits your throat.
$n circles around $N and slits $S throat.
You move too slowly to circle $N.
$n moves too slowly to circle around you.
$n moves too slowly to circle around $N.
You circle around $N and cause great damage with a surprise attack.
$n circles around you and causes great damage with $s surprise attack.
$n circles around $N and causes great damage with $s surprise attack.
Get real.  You can't circle $n. $e's a god!
$N, the fool, tried to circle you!
$N, the fool, tried to circle $n!
* Stun
M
 19
Your wicked stun leaves $N as a corpse.  Bleeding from $S eyes.
$n delivers a fatal stunning blow to you.
$n delivers a fatal stunning blow to $N, leaving only a corpse, bleeding from it's empty eye sockets.
$N avoids your stun.  You stumble and fall.
You avoid being stunned by $n who tumbles to the ground.
$N avoids $n's stun.  $n tumbles to the ground.
$N is devastated by your stunning blow.  $S eyes glaze over.
$n hammers you with a stunning blow.  You feel helpless and dizzy.
$n hammers $N with a stunning blow.  $N looks dizzy and glassy-eyed.
Stun a god?  Nah.
$n foolishly tries to stun you.
$n foolishly tries to stun $N.  Punk.

* Eyegouge
M
 21
$N looks just a little surprised as you jam your fingers deep into $S eye sockets, causing $S immediate death.
$n jams his hand deep into your eyes, causing your immediate demise.
$n jams his fingers deep into the eye sockets of $N, causing the immediate death of $N.
$N jumps back out of reach as you try to jam your fingers into $S eyes.
$n tries to gouge your eyes, but you are able to avoid $s attack!
$n attempts to eyegouge $N, but is unable to reach that far.
$N screams in pain as you jam your fingers into $S eyes!
Suddenly, $n jams his fingers in your eyes!  Gah!  You are blinded!
$n jams his fingers in the eyes of $N, blinding $M!
Eyegouge a God?  Are you stupid or something?  Gods can see with their eyes closed anyway - everyone knows that.
$n seems to want to play the Three Stooges with you...  maybe you should play, too.
$n attempts to blind $N with an eyegouge, uh.....  yeah.   Right.
* DirtThrow
M
 22
The dirt mixes with tears as $N meets $S maker.  $N is dead.
$n throws a handful of dirt into your eyes.  In your weakened state, this overcomes you.
$n throws a handful of dirt into your eyes.  In $S weakened state, this proves to be too much.
$N avoids your dirt throw.
$n tries to throw dirt in your eyes, but you are able to avoid $s attack!
$n attempts to throw dirt in $N's eyes, but misses.
$N screams in pain as you throw a handful of dirt into $S eyes!
$n throws dirt in your eyes, blinding you!
$n throws dirt in $Ns eyes, blinding $M!
Dork.  You can't do that to a god!
$n attempts to throw dirt in your eyes.  Dork.
$n attempts to throw dirt in $N's eyes.  Dork.
* Trip
M
 25
You skillfully trip $N who falls dead to the ground.
$n trips $N who falls dead to the ground.
$N trips you.  You tumble to ground and die!
You reach out with your foot and attempt to trip $N, but $E sees your ploy and avoids your foot.
$n tries to trip you, but you avoid $s outstretched foot.
$n tries to trip $N, but $N is too quick.
$N trips over your foot, landing on the ground with a THUD!
$n trips you and you fall!
$n trips $N, causing $N to fall!
$N looks at you with pity and pats you on the head.
You realize that $n is trying to trip you.  *sigh*  There's one in every crowd.
$n attempts to trip $N.  Good thing $n is in a good mood today.
* Groinkick
M
 29
You wind up and kick $N in the groin so hard that $E does not recover from the 'blow'.  $N is dead!
$n kicks you with such force in the groin that you decide that going on with life would not be worth it.  You sink into death gladly.
$n kicks $N in the groin so hard that $N's eyes roll back up in $S head and $E dies!
Your attempt to kick $N in the groin uses such force that when you miss him you lose your footing and have to take a moment to regain your balance.
Lucky for you, $n misses his kick in your groin by scant inches!
$n winds up a whopper of a shot on $N's groin, but misses and almost falls over.
You foot plows mercilessly into $N's groin, causing $S eyes to roll up into $S head as $E staggers backward.
$n kicks you a stunning blow to the groin, causing the world around to explode with bright lights and a loud buzzing noise.
$n gets a running start as $e slams $s foot into $N groin, causing $N to gasp and make strangled, half coherent noises.
I think a bitchslap may be coming for that one.
$n!  That little rodent just tried to kick you in the groin!
$N's eyes get very wide as $E realizes that $n just tried to punt $m in the groin.
* Brain
M
 30
You slam your palm into $N's nose, slamming shards of bone deep into $S brain, causing $N to die.
$n slams $s palm up into your nose, shoving the cartilage into your brain and puncturing most of the vital areas therein.  You are dead.
$n slams the palm of $s hand into $N's nose, shoving the cartilage into $N's brain.  $N is dead.
Your attempt to slam your palm into $N's nose is a complete failure.  You missed.
$n tries to slam $s palm into your nose, but $s hand goes sailing by.
$n tries to slam his palm into $N's nose, but misses completely.
You slam your palm into $N's nose, causing a steady flow of bloody snot.
$n slams $s palm into your nose, making your nose into a mushy, bloody mess.
$n slams $s palm into $N's nose, making $N's nose into a mushy, bloody mess.
You attempt to hit $N.  $E merely looks at you, as if waiting for something more.
$n tries to hit you. Maybe a bitchslap is in order?
$n tries to hit $N. Not a chance. 

* Mother Earth
M
 35
Mother Earth blasts a tremendous force into $N, causing $S death.
Mother Earth rises at $n's bidding, delivering a killing blow.
Mother Earth rises at $n's bidding, delivering a killing blow to $N!
You attempt to call Mother Earth to your aid, but she cannot hear you.
$n attempts to call Mother Earth to $s aid, but fails in $s attempt.
$n attempts to call Mother Earth to $s aid, but fails in $s attempt.
Mother Earth blasts $N with tremendous force.
Mother Earth blasts you with tremendous force!
Mother Earth blasts $N with tremendous force.
Do you really believe that Mother Earth would harm $N?
Mother Earth bows before you, turning an apologetic glance at $n.
Mother Earth bows before $N, turning an apologetic glance at $n.

* Tangle Weed
M
 46
Your tangle weeds rip into $N, causing $S death.
Tangle weeds rise at $n's bidding, tearing you to shreds.
Tangle weeds rise at $n's bidding, tearing $N to shreds!
You attempt to call a tangle weed to assist you, but they don't seem to care.
$n attempts to call tangle weeds to $s aid, but fails in $s attempt.
$n attempts to call tangle weeds to $s aid, but fails in $s attempt.
Tangle weeds ensnare $N and tear at $S skin!
Tangle weeds ensnare you and tear at your skin!
Tangle weeds ensnare $N and tear at $S skin!
Do you really believe that tangle weeds would harm $N?
The tangle weeds say $n is a dork.
The tangle weeds say $n is a dork.

* Roundhouse
M
 48
Your roundhouse kick snaps $N's neck cleanly. $E falls in a lifeless heap.
$n snaps your neck with a roundhouse kick.
$n spins and delivers a fatal roundhouse kick, snapping $N's neck.
Your flying roundhouse kick misses $N by a country mile.
$n spins through the air and a poorly executed attempt to kick you with a roundhouse.
$n spins through the air and a poorly executed attempt to kick $N with a roundhouse.
You rock $N backwards with a perfectly executed roundhouse kick.
$n sends you flying backwards with a perfectly executed roundhouse kick.
$n sends $N flying backwards with a perfectly executed roundhouse kick.
$N laughs at your petty attempt to kick $M.
You can only laugh at $n's pathetic attempt to cause you harm.
$n is stupid.

* kickflip
M
 49
Your kickflip decapitates $N! $E falls in a lifeless heap.
$n decapitates you with a devastating kickflip.
$n flips head over heels, decapitating $N in the process.
You attempt to kickflip, but end up landing on your head.
$n attempts to proform a kickflip against you, but ends up landing on $s head.
$n attempts to kickflip $N but, ends up landing on $s head.
You flip head over heels kicking $N onto $S butt in the process!
$n flips head over heels kicking you onto your butt!
$n flips head over heels, kicking $N onto $S butt in the process!
$N laughs at your petty attempt to kick $M.
You can only laugh at $n's pathetic attempt to cause you harm.
$n is stupid.

* Chop * Where'd this come from? * 
M
 50
You side-swing your hand full force into $N's throat, causing $M to choak on $S crushed windpipe and die!
$n swings $s hand sideways into $N's throat, crushing $S windpipe, killing $M instantly!
$n slams $s hand sideways into your throat, crushing your windpipe.
You swing with all your force at $N, but miss by just a slight bit.
$n swings at you with the side of his hand, but misses narrowly.
$n swings at $N with the side of $s hand, but misses.
$N staggers back from the solid /ccchop/c0 you deliver to him.
$n /ccchops/c0 you soundly with the flat of $s hand.
$N staggers slightly from the /ccchop/c0 $n delivers.
Yeah, right... chop all you like. You'll be lucky to get away unbitchslapped.
Seems as though $n might be trying some martial arts on yo ass - bitchslap, please?
Tsk tsk. Only a fool attempts to harm a God. 

* Shield Punch
M
 52
You slam $N with you shield so hard that you kill $M!
$n slams you so hard with $s shield that $e kills you!
$n slams $N so hard with his shield that $e kills $M!
You attempt to hit $N with your shield, but you miss.
$n tries to hit you with $s shield, but misses.
$n tries to hit $N with $s shield, but misses.
You slam $N with your shield!
$n slams you with $s shield!
$n slams $N with $s shield!
Try that some other time... on a mortal.
$n raises $s shield as if to hit you with it, but changes $s mind...
$n thinks twice about hitting $N with $s shield.

* Backslash
M
 54
You spin around in a deft move and slash $N. $E is dead!
$n spins around in a deft move and slashes you through the belly. You are dead.
$n spins around in a deft move and slashes $N through the belly.
You spin around and attempt to slash $N, but miss.
$n spins around and attempts to slash you, but miss.
$n spins around and attempts to slash $N, but misses.
You spin around and slash $N!
$n spins around and slashes you!
$n spins around and slashes $N!
Get real.  You can't slash $n. $e's a god!
$N, the fool, tried to slash you!
$N, the fool, tried to slash $n!

* Uppercut
M
 55
You slam your fist into $N's jaw so hard that $E is killed!
$n slams $s fist so hard into your jaw that you are killed!
$n slams $s fist so hard into &N's jaw that $E is killed!
You swing a massive uppercut, but miss.
$n swings a massive uppercut, but misses.
$n swings a massive uppercut, but misses.
You slam your fist in an arc, slamming it into $N's jaw.
$n slams $s fist in an arc, slamming it into your jaw.
$n slams $s fist in an arc, slamming it into $N's jaw.
Get real.  You can't hit $n. $e's a god!
$N, the fool, tried to hit you!
$N, the fool, tried to hit $n! 

* Charge!!
M
 56
You charge into battle, killing $N upon impact!
$n charges into battle, killing you on impact!
$n charges into battle, killing $N on impact!
You charge into battle boldly, but miss your target.
$n charges boldly into battle, but misses you in $s attack.
$n charges boldly into battle, but misses $s target.
You charge into battle, slamming $N with a bold attack!
$n charges into battle, slamming you with a bold attack!
$n charges into battle, slamming $N with a bold attack!
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to attack you!
$N, the fool, tried to attack $n!

* Drown
M
 59
You force $N's head under the water and don't let go.
$n forces your head under the water and doesn't let up.
$n forces $N's head under the water and doesn't let up.
You try to drown $N, but he flails around to much for you to get a grip.
$n tries to drown you, but you flail away.
$n tries to drown $N, but $E flails about to much.
You force $N's head under the water and laugh.
$n forces your head under water and laughs.
$n forces $N's head under the water and laughs.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* BLADED FURY
M
 60
Your furious assault takes $N off guard, and $E falls to your attack.
$n's furious assault takes you by surprise - you have been vanquished.
$n's furious takes $N by surprise - $N has been vanquished.
Your attack goes wide, missing $N.
$n's attack goes wide, missing you.
$n's attack goes wide, missing $N.
Your fury drives $N back, your blade a blur of damaging motion.
$n's fury drives you back, $s blade a blur of damaging motion.
$n's fury drives $N back, $S blade a blur of damaging motion.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* POWER SLASH
M
 61
You swing a mighty blow with your weapon, slicing $N's head off.
$n swings a mighty blow with $s weapon, slicing your head off.
$n swings a mighty blow with $s weapon, slicing $N's head off.
You swing a mighty blow at $N, but miss.
$n swings a mighty blow at your head, but misses.
$n swings a mighty blow at $N's head, but misses.
You swing a wide slash at $N, slicing $M open, blood everywhere.
$n swings a wide slash to your midsection, laying you open.
$n swings a wide slash to $N's midsection, laying $M open.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* SWARM
M
 62
A swarm of poisonous locusts fly in, killing and maiming $N.
$n calls in a swarm of poisonous beetles, their deadly stings killing you.
$n calls in a swarm of poisonous beetles which sting $N to death!
You call for a swarm to aid you, but swarm is forthcoming.
$n raises his voice in a strange call, but is not answered.
$n raises his voice in a strange call, but is not answered.
A swarm of wasps come to your call, stinging $N horribly.
A swarm of wasps come to $n's call, stinging you horribly.
A swarm of wasps come to $n's call, stinging $N horribly.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* ELEMENTAL FURY
M
 63
Your cry to the elements is answered, leaving $N dead on the ground.
$n cries to the elements and they respond, leaving you dead on the ground.
$n cries to the elements and they respond, leaving $N dead on the ground.
Your cry to the elements goes unheard.
$n's cry to the elements goes unheard.
$n's cry to the elements goes unheard.
You are answered, the elements of the world rising up to strike $N.
$n calls to the elements, which rise up and strike you.
$n calls to the elements, which rise up and strike $N.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* MONSOON
M
 64
A furious gale bowls $N over, knocking $S head hard enough to kill $M.
A furious gale bowls you over, knocking your head hard enough to kill you.
A furious gale bowls $N over, knocking $S head hard enough to kill $M.
You cry to the Gods of the wind, however not even a gust comes in response.
$n looks disappointed as he issues an unanswered cry.
$n looks disappointed as he issues an unanswered cry.
A furious gale bowls $N over, doing $M some damage in the process.
A furious gale bowls you over, doing you some damage in the process.
A furious gale bowls $N over, doing $M some damage in the process.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $N!

* TACKLE
M
 65
You fly through the air, landing on $N, crushing the life from $M.
$n flies through the air, landing on you, crushing the life from you.
$n flies through the air, landing on $N, crushing the life from $M.
You overshoot your target, flying past $N.
$n tries to tackle you, but misses and lands in a tangle.
$n tries to tackle $N, but misses $M and lands in a tangle.
You jump into the air, throwing yourself on $N.
$n jumps through the air, throwing $mself on you.
$n jumps through the air, throwing $mself on $N.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* PRESSURE
M
 66
You find the one spot on $N that can not take the pain.
$n digs $s fingers into your shoulder, finding a killing spot.
$n digs $s fingers into $N's shoulder, watching as $N slowly dies.
You try to find a pressure point on $N, but fail.
$n reaches for you, but does not connect.
$n reaches for $N, but does not connect.
$N screams in pain as you dig your fingers into $S shoulder.
You scream in pain as $n digs $s fingers into your shoulder.
$N screams in pain as $n digs $s fingers into $N's shoulder.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* KI
M
 67
You cry your attack as you delivering a killing blow to $N.
$n cries $s attack as $e delivers you a killing blow.
$n cries $s attack as $e delivers $N a killing blow.
You cry you attack, but fail to deliver the blow.
$n cries $s attack, but fails to connect with the blow.
$n cries $s attack, but fails to connect with the blow.
You give an ancient cry of battle as you attack $N.
$n gives an ancient cry of battle as $e attacks you.
$n gives an ancient cry of battle as $e attacks $N.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* HEADCUT
M
 68
You slice through $N's throat, killing $M.
$n slices through your throat, killing you.
$n slices through $N's throat, killing $M.
You try to cut at $N's head, but miss.
$n aims a cut at your head, but misses.
$n aims a cut at $N's head, but misses.
You cut across $N's temple, causing serious damage.
$n cuts across your temple, causing serious damage.
$n cuts across $N's temple, causing serious damage.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* KAMIKAZE
M
 69
Without heed for your own safety you attack $N, killing $M.
Without heed for $s own safety $n attacks you, killing you.
Without heed for $s own safety $n attacks $N, killing $M.
Without heed for your own safety you attack $N, but miss.
Without heed for $s own safety $n attacks you, but misses.
Without heed for $s own safety $n attacks $N, but misses.
Without heed for your own safety you attack $N, hurting $M badly.
Without heed for $s own safety $n attacks you, hurting you badly.
Without heed for $s own safety $n attacks $N, hurting $M badly.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* HEADBUT
M
 70
You slam your head into $N's head, killing $M.
$n slams $s head into your own head, killing you.
$n slams $s head into $N's head, killing $M.
You try to headbut $N, but miss.
$n tries to headbut you, but misses.
$n tries to headbut $N, but misses.
You slam your head into $N's, causing $M exploding pain.
$n slams $s head into your head, causing exploding pain.
$n slams $s head into $N's, causing exploding pain.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* BEARHUG
M
 71
You grab $N in a bearhug and squeeze the life from $M.
$n grabs you in a bearhug and squeezes the life from you.
$n grabs $N in a bearhug and squeezes the life from $M.
You reach for $N, but $E dance out of reach.
$n tries to grab you in a bearhug, but you dance out of reach.
$n tries to grab $N in a bearhug, but $N dances out of reach.
You grab $N in a bearhug and squeeze $M painfully.
$n grabs $N in a bearhug and squeezes you painfully.
$n grabs $N in a bearhug and squeezes $M painfully.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* BODYSLAM
M
 72
You lift $N over your head, throwing $M to the ground, killing $M.
$n lifts you over $s head, throwing you to the ground, killing you.
$n lifts $N over $s head, throwing $M to the ground, killing $M.
You try to get a firm grip on $N, but are unable.
$n tries to get a firm grip on you, but is unable.
$n tries to get a firm grip on $N, but is unable.
You lift $N over your head, throwing $M to the ground.
$n lifts you over $s head, throwing you to the ground.
$n lifts $N over $s head, throwing $M to the ground.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* Swat
M
 75
You swat $N with such force you squish $M!
$n swats you with such force $e squishes you!
$n swats $N with such force $e squishes $M!
You try to swat $N, but miss.
$n tries to swat you, but misses.
$n tries to swat $N, but misses.
You swat $N like the puny bug he is.
$n swats you away like a puny bug.
$n swats $N away like a puny bug.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* Stomp
M
 76
You stomp $N straight into the ground!
$n stomps you straight into the ground!
$n stomps $N straight into the ground~
You try to stomp $N, but miss.
$n tries to stomp you, but misses.
$n tries to stomp $N, but misses.
You stomp on $N's head!
$n stomps on your head!   /cROUCH!/c0
$n stomps on $N's head!
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* Trick punch
M
 77
Your trick punch must have hit a soft spot - you killed $M!
$n's trick punch lands just right - you are dead!
$n' trick punch lands just right - $N is dead!
You try and slap $N around a little, but miss every punch.
$n tries to give you a few kidney shots, but misses every one.
$n tries to give $N a few kidney shots, but misses every one.
You skip in a few good punches, dealing some light damage to $N.
$n slips in a few good punches, dealing you some light damage.
$n slips in a few good punches, dealing $N some light damage.
Feeling tricky today, are we? Hitting $N would be a helluva trick!
$n seems to be feeling a bit tricky today...
$n does a three stooges on $N, but ends up hurting $mself.

* Low Blow
M
 78
You land a very dirty hit just in the right spot, killing $N.
$n lands a very dirty hit just in the right spot, killing you.
$n lands a very dirty hit just in the right spot, killing $N.
Your attempt at a dirty move results in a wide swing and a miss.
$n's attempt at a dirty move results in a wide swing and a miss.
$n's attempt at a dirty move results in a wide swing and a miss.
You swing and connect with a very mean, very low-down hit to $N.
$n swings and connects with a very mean, very low-down hit to you.
$n swings and connects with a very mean, very low-down hit to $N.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* Knee
M
 79
Your well-placed knee was all $N could take - you've killed $M.
$n's well-placed knee was all you could take - $e has killed you.
$n's well-placed knee was all $N could take - $n has killed $N.
You try to slam $N with your knee, but miss.
$n tries to slam you with $s knee, but misses.
$n tries to slam $N with $s knee, but misses.
You slam you knee into $N's gut, knocking the wind from $M.
$n slams $s knee into your gut, knocking the wind from you.
$n slams $s knee into $N's gut, knocking the wind from $M.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* Psychotic Stabbing
M
 88
Your maniacal stabbing gets the best of $N - $E is dead!
$n's maniacal stabbing is just too much - you die.
$n's maniacal stabbing is just too much - $N dies.
You throw yourself at $N in a frenzy of stabbing, missing by inches.
$n throw $mself at you in a frenzy of stabbing, missing you by inches.
$n throws $mself at $N in a frenzy of stabbing, missing by inches.
You scream in a high-pitched battle-cry, stabbing $N frantically.
$n screams in a high-pitched battle-cry, stabbing you frantically.
$n screams in a high-pitched battle-cry, stabbing $N frantically.
YOU DON'T STAB GODS. Got it?
You pat $n on $s little head, tsk tsking his performance.
$N pats $n on $s little head, tsk tsking $s performance.

* Trample
M
 94
Your mount's hooves do such damage to $N that it kills $M!
$n's mount's hooves maul you to death!
$n's mount's hooves maul $N to death!
Your skills with your mount are not enough to trample $N.
$n attempts to guide $s mount to trample you, but fails.
$n attempts to guide $s mount to trample $N, but fails.
Your mount's hooves maul $N in a frenzy of motion, knocking $M down.
$n's mount's hooves maul you in a frenzy of motion, knocking you down.
$n's mount's hooves maul $N in a frenzy of motion, knocking $M down.
Leave $M alone - $E is such a nice god...
You might want to give $n a bit of a bitchslap...
$N warms up $S bicthslapping hand for $n.

$
