
* Gods Fury
M
 5
/cCThe fury of Gods is visited upon $N. $E has been slain!/c0
/cRThe fury of the Gods is visited upon you fully. You have been slain!/c0
/crThe fury of Gods is visited upon $N. $E has been slain!/c0
/cY$N silently pleads, gazing skyward as the Gods' fury is hurtled at $m./c0
/cWThe realization that the power of the Gods has been hurtled at you comes just in time!/c0
/cw$N silently pleads, gazing skyward as the Gods' fury is hurtled at $m./c0
/cCThe fury of the Gods blasts $N with amazing force./c0
/cRYou are blasted with all the fury of the Gods./c0
/crThe fury of the Gods blasts $N with amazing force./c0 
Dumbass... $N *is* a God...
Puny mortal. $e asks for your own wrath to be visited upon... yourself?
$N gives $n a a sidelong look and a smirk.

* Dispel Good
M
 7
/cC$N is dissolved by your evil./c0
/cR$n dissolves you -- the price paid for leading a good life -- you die.../c0
/cr$n completely dissolves $N!/c0
/cY$N is unaffected by your evil!/c0
/cW$n thinks that $e is really evil, and tries to dispell you./c0
/cw$N laughs at $n as $e tries to dispell $M!/c0
/cC$N shivers and suffers from $S goodness!/c0
/cR$n makes your soul hurt and suffer!/c0
/cr$n makes $N's good spirit shiver and suffer!/c0
Did you really expect $M to suffer?
$n unfruitfully tries to dispell you.
$n is stupid...

* Dispel Evil
M
 8
/cC$N is dissolved by your goodness./c0
/cR$n dissolves you, you regret having been so evil, and die.../c0
/cr$n completely dissolves $N!/c0
/cY$N is unaffected by your goodness!/c0
/cW$n thinks that $e is really good, and tries to dispell you./c0
/cw$N laughs at $n as $e tries to dispell $M!/c0
/cC$N shivers and suffers from $S evilness!/c0
/cR$n makes your soul hurt and suffer!/c0
/cr$n makes $N's evil spirit shiver and suffer!/c0
Did you really expect $M to suffer?
$n unfruitfully tries to dispell you.
$n is stupid...

* Harm
M
 9
/cCAs you finish the incantation of the spell, $N falls dead due to the amount of harm $E takes!/c0
/cRYou feel light headed as $n completes a spell which causes you so much harm that you just /crsnuff it./c0
/cYAs $n touches $M, $N takes the full brunt of a harm spell and collapses.  Dead./c0
/cWSwinging out at $N, you miss and your harm spell goes off harmlessly./c0
/cwYou duck out of the way of $n and $s harm spell misses you./c0
/cCShowing remarkable dexterity, $N avoids $n's reach and subsequent harm spell./c0
/cRYou watch the pained expression on $N's face as you hit $M with your harm spell./c0
/crYou grimace in pain as $n's harm spell strikes you./c0
A large grin crosses $n's face as $s harm spell causes $N grievous pain.
Harm a god?  Are you serious?  Of course $N avoids is casually.
$n tries to harm you.  Poor sod.
What a buffoon!  $n looks somewhat perturbed as $N ignores the recently cast harm spell.

* Earthquake
M
 22
/cCThe earth opens beneath $N's feet and swallows $M whole!/c0
/cRThe earth opens beneath your feet and swallows you whole!/c0
/crThe earth opens beneath $N's feet and swallows $M whole!/c0
/cY$N desperately tries to keep $S balance as the earth shakes beneath $S feet!/c0
/cWYou desperately try to keep your balance as the earth shakes beneath your feet!/c0
/cw$N desperately tries to keep $S balance as the earth shakes beneath $S feet!/c0
/cRThe earth rumbles hard enough to do damage to $N!/c0
/cRYou are damaged by the rumbling earth!/c0
/cr$N is damaged by the rumbling earth!/c0
$N gracefully levitates as the earth shifts beneath $S feet under $M./c0
You gracefully levitate as the earth shifts underneath you./c0
$N gracefully levitates as the earth shifts beneath $S feet under $M./c0

* Call Lightning
M
 23
/cCYour lightning bolt kills $N!/c0
/cRYou are electrocuted to death by a lightning bolt sent by $n!/c0
/crThe dead body of $N sizzles in the heat from a lightning bolt sent by $n!/c0
/cYYour lightning bolt scores the ground in front of $N, a misser!/c0
/cWThe ground before you is scored as $n misses you with lightning!/c0
/cw$N jumps backwards in time to avoid lightning sent by $n!/c0
/cCYou hit $N with your lightning, bullseye!/c0
/cRYou are hit by lightning sent by $n, OUCH!/c0
/cr$N screams in pain as lightning from $n penetrates $M!/c0
$N stops your lightning with a single gesture, BEWARE!!!
You stop $n's lightning with a sure hand, no time for children's games...
$n's lightning disappears as $N makes a simple gesture.

* Hand of Balance
M
 30
/cCYou barely begin your prayer before $N gives one final gasp and dies./c0
/cR$n barely begins $s prayer before you realize it is too late. You are dead!/c0
/cr$n begins praying feverishly, calling upon $s God to kill $N./c0
/cYYour prayer goes unheard./c0
/cW$n recites a prayer but to no avail./c0
/cw$n recites a prayer but to no avail./c0
/cCYour prayer is heard and answered - $N staggers under the impact./c0
/cRYou stagger under the impact of $n's prayer./c0
/cr$n staggers under the impact of $n's prayer./c0
Get real.  You can't even think about $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n! 

* ELEMENTAL BURST
M
 31
/cCYou call to the elements - fire, sun, earth and wind killing $N./c0
/cRA great burst of elemental power slams into you, killing you./c0
/crA great burst of elemental power slams into $N, killing $M/c0
/cYYour call to the elements goes unheard./c0
/cW$n calls to the elements, but $s call goes unheard./c0
/cw$n calls to the elements, but $s call goes unheard./c0
/cCA burst of elemental power surges forth, slamming into $N./c0
/cRA great burst of elemental power slams into you./c0
/crA great burst of elemental power slams into $N./c0
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* WINDS OF PAIN
M
 32
/cCWinds of pain tear into $N, killing $M on impact./c0
/cRWinds of pain tear into your soul, killing you on impact./c0
/crWinds of pain tear into $N, killing $M on impact./c0
/cYA slight stirring of a breeze is the only response you get./c0
/cW$n's call to the gods of the air goes unheard./c0
/cw$n's call to the gods of the air goes unheard./c0
/cCWinds of pain tear at $N!/c0
/cRWinds of pain tear at you!/c0
/crWinds of pain tear at $N!/c0
Get real.  You can't hurt $n. $e's a god!/c0
$N, the fool, tried to hurt you!/c0
$N, the fool, tried to hurt $n!/c0

* SPIRIT STRIKE
M
 33
/cCThe spirits of all that is holy come to your aid, striking $N down./c0
/cRThe spirits of all that is holy come to $n's aid, striking you down./c0
/crThe spirits of all that is holy come to $n's aid, striking $N down./c0
/cYThe spirits do not heed your call./c0
/cWThe spirits fail to answer $n's call./c0
/cwThe spirits fail to answer $n's call./c0
/cCThe spirits of all that is holy come to your aid, striking $N./c0
/cRThe spirits of all that is holy come to $n's aid, striking you./c0
/crThe spirits of all that is holy come to $n's aid, striking $N./c0
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* ABOMINATION
M
 34
/cCYou call upon the holy gods, their awesome power killing $N./c0
/cR$n calls upon the holy gods, their awesome power killing you./c0
/cr$n calls upon the holy gods, their awesome power killing $N./c0
/cYYour call to the gods goes unheard./c0
/cW$n's call to the gods goes unheard./c0
/cw$n's call to the gods goes unheard./c0
/cCYou call to the gods, their awesome power dealing $N a powerful blow./c0
/cR$n calls to the gods, their awesome power dealing you a powerful blow./c0
/cr$n calls to the gods, their awesome power dealing $N a powerful blow./c0
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* WINDS OF RECKONING
M
 35
/cCThe Winds of Reckoning blast through $N, carrying $S soul away with them./c0
/cRThe Winds of Reckoning blast through you, taking your soul with them./c0
/crThe Winds of Reckoning blast through $N, carrying $S soul away with them./c0
/cYThere is not even a slight puff of air. Nothing./c0
/cW$n seems to have failed in $s most recent prayer./c0
/cw$n seems to have failed in $s most recent prayer./c0
/cCThe Winds of Reckoning blast into $N!/c0
/cRThe Winds of Reckoning have come for you!/c0
/crThe Winds of Reckoning blast into $N!/c0
Get real.  You can't hurt $n. $e's a god!/c0
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* ANGEL BREATH
M
 36
/cCYou breath the power of the angels upon $N, killin $M instantly./c0
/cR$n breathes the power of the angels upon you, killin you instantly./c0
/cr$n breathes the power of the angels upon $N, killin $M instantly./c0
/cYYour angelic breath does nothing but sweeten the air./c0
/cWMmm, $n has minty-fresh breath today!/c0
/cwMmm, $n has minty-fresh breath today!/c0
/cCYour angelic breath throws $N backward, causing heavy damage./c0
/cR$n's angelic breath throws you backward, causing heavy damage./c0
/cr$n's angelic breath throws $N backward, causing heavy damage./c0
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* SOULSCOURGE
M
 37
/cCYou pray to cleanse the soul of $N, but instead get $M killed!/c0
/cR$n prays to cleanse your soul, but you would rather die than let that happen./c0
/cr$n's prayer kills $N without ceremony./c0
/cYYour prayer does nothing to cause $N any pain./c0
/cW$n's prayer only gives you a feeling of peace, nothing more./c0
/cw$n prays devoutly, but nothing happens./c0
/cCYou pray to rend through $N's soul, causing $M great pain!/c0
/CR$n's prayer reaves through your soul, causing you great pain!/c0
/cr$n's prayer reaves through $N's soul, causing $M great pain./c0
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* PLAGUE
M
 38
/cCA terrible plague is visited upon $N, its full force killing $M./c0
/cRA terrible plague is visited upon you, its full force killing you./c0
/crA terrible plague is visited upon $N, its full force killing $M./c0
/cYYour prayer to call a plague upon $N goes unanswered./c0
/cW$n makes a devout prayer to $s gods, but they do not respond./c0
/cw$n makes a devout prayer to $s gods, but they do not respond./c0
/cCA terrible plague is visited upon $N, doing terrible damage!/c0
/cRA terrible plague is visited upon you, doing terrible damage!/c0
/crA terrible plague is visited upon $N, doing terrible damage!/c0
Get real.  You can't hurt $n. $e's a god!/c0
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* EXORCISM
M
 46
You wash away the darkest evils in $N's soul, killing $M in the process!
You writhe in agony, dying, as $n excorcises the evil in your soul!
$N writhes in agony, dying, as $n excorcises the evil in $S soul!
$N is not of an evil temperament, your excorcism has no affect.
$n attempts to excorcise the evil within you, however you are too goodly.
$N attempts to exorcise the evil within $N, but with no affect.
$N writhes in agony as you excorcise the evil in $S soul!
You writhe in agony as $n excorcises the evil in your soul!
$n writhes in agony as $n excorcises the evil in $S soul!
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n! 

* HEAVENS BEAM
M
 48
The light of heaven completely disintegrates $N!
The light of heaven is too much for you, you are dead!
The light of heaven is too much for $N, $E is dead!
$N remains unaffected by the light of heaven.
The light of heaven washes over you, causing no damage.
The light of heaven washes over $N, causing no visible damage.
The light of heaven shines over $N, fighting against $S evil!
The light of heaven shines over you, fighting against your evil!
The light of heaven shines over $N, fighting against $S evil!
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!  

$

