* Dibrova-style messages file.  The structure is identical to
* CircleMUD 3.0, with the difference being that we keep 
* separate lists for various messages.  Each list is loaded
* from it's own file.
*
* Messages for spells.

***************************************************************************
*                           Offensive Spells                              *
***************************************************************************

* Burning Hands
M
 5
/cRYou have burned $N to death!/c0
/cRYou have been burned to death by $n!/c0
/cr$n has burned $N to death!/c0
/cYYou miss $N with your burning hands./c0
/cW$n reaches for you with burning hands, but misses!/c0
/cw$n tries to burn $N, but $E escapes!/c0
/cCYou burn $N with your hot little hands!/c0
/cRYou cry out in pain as $n grabs you with burning hands!/c0
/cr$N cries out as $n burns $M!/c0
Your attempt to burn $N nears BLASPHEMY!!!/c0
The pitiful creature before you tries to burn you./c0
Unaware of the risks, $n tries to burn $N./c0

* Call Lightning
M
 6
/cCYour lightning bolt kills $N!/c0
/cRYou are electrocuted to death by a lightning bolt sent by $n!/c0
/crThe dead body of $N sizzles in the heat from a lightning bolt sent by $n!/c0
/cYYour lightning bolt scores the ground in front of $N, a misser!/c0
/cWThe ground before you is scored as $n misses you with lightning!/c0
/cw$N jumps backwards in time to avoid lightning sent by $n!/c0
/cCYou hit $N with your lightning, bullseye!/c0
/cRYou are hit by lightning sent by $n, OUCH!/c0
/cr$N screams in pain as lightning from $n penetrates $M!/c0
$N stops your lightning with a single gesture, BEWARE!!!
You stop $n's lightning with a sure hand, no time for children's games...
$n's lightning disappears as $N makes a simple gesture.

* Chill Touch
M
 8
/cCYou chill $N, remember to put flowers on $S grave.../c0
/cRYou feel chilled by $n and then you feel no more -- R.I.P./c0
/cr$n touches $N who slumps to the ground as a dead lump, rather chilly isn't it?/c0
/cYThe atmosphere turns chilly as you miss $N!/c0
/cWYou dodge $n and $s chill touch!/c0
/cw$n tries unsuccesfully to chill $N!/c0
/cCYou chill $N!/c0
/cRYou feel your life flowing away as $n chills you!/c0
/cr$n chills $N who suddenly seem less lively!/c0
Are you trying to chill $N? -- what a joke!!/c0
$n tries to chill you, what a laugh...
$N starts to laugh as $n turns chilly!

* Color Spray
M
 10
/cCYOU KILLED $N!!! -- don't you feel ashamed.../c0
/cRYour head is filled with all the colors of the rainbow before it bursts!/c0
/cr$n makes $N into a colorful corpse!/c0
/cYYour spray of color misses $N -- what a dull world.../c0
/cW$n unsuccesfully tries to add color to your life!/c0
/cw$n splashes color everywhere except $N./c0
/cCYour own private rainbow hits $N in the face -- WOWIE!!/c0
/cRA sudden burst of colors sends you reeling!/c0
/cr$n throws colors at $N who in vain tries to escape!/c0
Your spray of colors turn into butterflies as $N frowns.
Your frown is enough to turn $n's color spray into little butterflies.
The air is filled with butterflies as $N frowns at $n's color spray.

* Dispel Evil
M
 22
$N is dissolved by your goodness.
$n dissolves you, you regret having been so evil, and die...
$n completely dissolves $N!
$N is unaffected by your goodness!
$n thinks that $e is really good, and tries to dispell you.
$N laughs at $n as $e tries to dispell $M!
$N shivers and suffers from $S evilness!
$n makes your soul hurt and suffer!
$n makes $N's evil spirit shiver and suffer!
Did you really expect $M to suffer?
$n unfruitfully tries to dispell you.
$n is stupid...

* Earthquake
M
 23
The earth opens beneath $N's feet and swallows $M whole!
The earth opens beneath your feet and swallows you whole!
The earth opens beneath $N's feet and swallows $M whole!
$N desperately tries to keep $S balance as the earth shakes beneath $S feet!
You desperately try to keep your balance as the earth shakes beneath your feet!
$N desperately tries to keep $S balance as the earth shakes beneath $S feet!
$N falls down and hurts $Mself!
You fall down and hurt yourself!
$N falls down and hurts $Mself!
$N gracefully levitates as the earth shifts beneath $S feet under $M.
You gracefully levitate as the earth shifts underneath you.
$N gracefully levitates as the earth shifts beneath $S feet under $M.

* Energy Drain
M
 25
$N crumples as you kill $M by draining $S energy!
As $n drains your last energy you look forward to the peace of the graveyard...
$n drains the energy of $N who crumples as a lifeless cocoon!
You need more draining lessons...
Luckily for you $n slept during draining-lessons!
$n fails to drain $N -- what a waste of energy!
You drain $N of some of $S energy!
You feel less energic as $n drains you!
$n drains $N -- what a waste of energy!
You waste energy trying to drain $N!
How amusing -- $n tries to drain you!
$N's eyes twinkle with laughter as $n tries to drain $M.

* Fireball
M
 26
Your fireball hits $N with full force, causing an immediate death!
As you burst into flames of death $n grins evilly...
The heat from a fireball from $n turns $N into a charred corpse!
Your fireball blooms few feet before $N who claps $S hands in wonder.
$n aims a fireball at you but it blooms few feet before you; you clap your hands at the show.
A fireball from $n misses $N -- what great fireworks around here!!
You throw a fireball at $N and have the satisfaction of seeing $M enveloped in flames!
You are enveloped in flames from a fireball sent by $n -- OUCH!!
$n smirks as $s fireball explodes into the face of $N!
How shameful to throw fireballs at a GOD!!!
You choose to ignore $n's shameful attempt to fireball you.
$n's fireball is tactfully ignored by $N.

* Harm
M
  27
As you finish the incantation of the spell, $N falls dead due to the amount of harm $E takes!
You feel light headed as $n completes a spell which causes you so much harm that you just snuff it.
As $n touches $M, $N takes the full brunt of a harm spell and collapses.  Dead.
Swinging out at $N, you miss and your harm spell goes off harmlessly.
You duck out of the way of $n and $s harm spell misses you.
Showing remarkable dexterity, $N avoids $n's reach and subsequent harm spell.
You watch the pained expression on $N's face as you hit $M with your harm spell.
You grimace in pain as $n's harm spell strikes you.
A large grin crosses $n's face as $s harm spell causes $N grievous pain.
Harm a god?  Are you serious?  Of course $N avoids is casually.
$n tries to harm you.  Poor sod.
What a buffoon!  $n looks somewhat perturbed as $N ignores the recently cast harm spell.

* Lightning Bolt
M
 30
Your lightning bolt shatters $N to pieces!
You feel enlightened by the lightning bolt $n sends, and then all is darkness -- R.I.P.!
$N recieves the full blast of a lightning bolt from $n... and is no more.
Your aim goes from bad to worse, and your lightning bolt misses $N!
$n has bad aim and $s lightning bolt misses you!
$n tries to hit $N with a lightning bolt but only hits the sky!
The lightning bolt hits $N with full impact!
YOU'RE HIT!  A lightning bolt from $n has reached its goal!
$N wavers under the impact of the lightning bolt sent by $n!
Your lightning bolt is extinguished as mighty $N moves $S ears!
You move your ears to extinguish $n's lightning bolt.
$N moves $S ears and $n's lightning bolt is extinguished!

* Magic Missile
M
 32
The magic missile tears away the remaining life of $N!
You only have time to notice $n uttering strange sounds before everything is dark!
The magic missile sent by $n causes $N to stagger and collaps in a lifeless heap!
The magic missile penetrates the air miles above $N.
You don't even have to duck as $n sends a magic missile way over your head.
$n tries in vain to correct the course of the magic missile meant to hit $N.
You watch with selfpride as your magic missile hits $N!
You stagger as a magic missile from $n hits you!
$n throws a magic missile at $N who staggers under the blow!
Your magic missile makes $N roar with laughter.
You can't help laughing as $n sends a magic missile at you.
$N starts to roar with laughter as $n sends a magic missile at $M.

* Shocking Grasp
M
 37
$N dies while looking rather shocked!
$n shocks you.  Unfortunately your heart can't stand it...
$n reveals with a shock that $N has left $S body!
$N rather shockingly evades your grasp!
You nimbly dodge a shocking grasp from $n!
$N shockingly evades the grasp of $n!
You get a good hold of the shocked $N!
You get a shock as $n gets too close to you!
$N looks shocked as $n grasps at $M!
You shockingly realize you can't shock $N...
These puny creatures are shocking at times...
The atmosphere gets loaded as $n tries to shock $N!

* Dispel Good
M
 46
$N is dissolved by your evil.
$n dissolves you -- the price paid for leading a good life -- you die...
$n completely dissolves $N!
$N is unaffected by your evil!
$n thinks that $e is really evil, and tries to dispell you.
$N laughs at $n as $e tries to dispell $M!
$N shivers and suffers from $S goodness!
$n makes your soul hurt and suffer!
$n makes $N's good spirit shiver and suffer!
Did you really expect $M to suffer?
$n unfruitfully tries to dispell you.
$n is stupid...

* Firestorm 
M
 58
You call a rain of fire down upon $N, incinerating $S body!
$n calls a rain of fire down upon you, incinerating your body!
$n calls a rain of fire down upon $N, incinerating $N's body!
$N withstands the burning embers of your firestorm.
You withstand the burning embers of $n's firestorm.
$N withstands the burning embers of $n's firestorm.
Your firestorm scorches $N's flesh!
$n's firestorm scorches your flesh!
$n's firestorm scorches $N's flesh! 
Did you really expect $N to suffer?
$n unfruitfully tries to cast a firestorm upon you.
$n is stupid...

* Demon Fire
M
 64
You call forth the demonfires to burn through $N's soul, killing $M!
$n calls forth the demonfires to burn through your soul, killing you!
$n calls forth the demonfires to burn through $N's soul, killing $M!
Your demonfires do no damage to $N!
$n's demonfires do no damage to you!
$n's demonfires do no damage to $N!
Your demonfires burn into $N's flesh!
$n's demonfires burn into your flesh!
$n's demonfires burn into $N's flesh!
You can't hurt a god, stupid.
$n tried to cast demonfire on you. Bitchslap, anyone?
$n is a moron, let's just leave it at that.

* Black Breath
M
 67
Your balack breath kills $N!
$n's black breath kills you!
$n's black breath kills $N!
Your black breath has no effect on $N!
$n's black breath has no effect on you!
$n's black breath has no effect on $N!
Your black breath sends $N reeling backward!
$n's black breath sends you reeling backward!
$n's black breath sends $N reeling backward!
You can't hurt a god, stupid.
$n tried to cast demonfire on you. Bitchslap, anyone?
$n is a moron, let's just leave it at that.

* Black Dart
M
 74
Your black dart explodes $N into smithereens!
$n's black dart slams into your body, ripping most of your major limbs from their sockets.
$n kills $N with a dart of black magic!
A trace of blackness is all you see as your black dart goes wide.
$n takes aim at you with a dart made of blackened magic and misses.
$n swiftly dodges $N's dart of blackened magic.
$N is thrown by the intense pain of your black dart.
$n lands a direct and PAINFUL hit on $N with $s dart of blackened magic.
$n rocks $N with a powerful dart of blackened magic.
Did you really expect $M to be affected by your puny magic?
$n tries to hit you with a black dart.  Dork.
$n is stupid... soooo stuuupid.

* Cause light wounds
M
 78
$N staggers under your spell's power and falls to the ground in a lifeless heap.
You are hit by a ferocious blast of power from $n.  You are dead!
$n unleashes a blast of power against $N, causing $S immediate death.
You try to inflict wounds upon $N, but your spell goes wide.
$n casts a spell your way, but does not aim well enough and misses you.
$n attempts to cause $N harm, but $s spell misses by some distance.
Your spell sends $N reeling!
You are hit full force by $n's spell!
$n's spell causes $N some little damage as it slams into $M.
You cannot do that to a God!
$n just tried to cast a spell on you!  Bitch-SLAP! Bitch-SLAP!
$N raises an eyebrow as $n tries to cast a spell on $M.

* Cuase critical wounds
M
 79
Your spell hits $N with such force that $E falls dead from the impact!
$n's spell explodes into your body, the impact causing your death.
$N dies from the violent explosion of $n's spell.
You miss $N with your spell.
You narrowly avoid getting hit by $n's spell.
$N avoids $n's spell by inches.
You blast $N with your spell, causing some serious damage!
You see stars as $n's spell blasts into you.
$N writhes in pain as $n's spell hits $M full force.
Oh, give it up.
When will those puny mortals ever learn not to trifle a God?
$N just shakes $S head and keeps on walking as $n tries to cast a spell on $M.

* Lay Hands
M
 80
$N's eyes get wide with shock and disbelief as you lay your hands upon $S chest, causing $S death.
$n lays $s hand upon your chest, stopping your heart and causing your death.
$n places $s hand on $N's chest, stopping $N's heart and causing $S death.
$N steps nimbly aside as you attempt to lay your hands upon $M.
You step aside from $n as $e attempts to lay $s hands upon you.
$N steps nimbly away from $n as $e attempts to lay $s hands on $N.
You lay your hands upon $N, causing $M to cry out in pain!
$n places $s hand on your chest, sending pain radiating through your body.
$N cries out in pain as $n lays $s hand on $N's chest.
A God is liable to take it pretty bad when a mortal attempts to touch $M.
You swat $n's hand away as $e attempts to lay $s hands upon your Holy Self.
$n swats $N's hand away and slaps $N a ringing blow as $N tries to lay $S hands upon $n.

* Holy Mace
M
 90
You swing a mace of righteous light into $N's body, killing $M!
$n swings a mace of righteous light into your body, killing you!
$n swings a mace of righteous light into $N's body, killing $M!
The holy mace swings wide of $N's body, missing $M!
$n's holy mace swings wide of your body, missing you!
$n's holy mace swings wide of $N's body, missing $M!
You swing a mace of holy light into $N, exploding damage into $M!
$n swings a mace of holy light into you, exploding damage onto you!
$n swings a mace of holy light into $N, exploding damage into $M!
Don't be a moron.
$n just tried to hurt you with a spell - holy mace - bitchslap?
$n is a moron. A big, fat moron.

* Sonic Wall
M
 92
$N collapses in a bloody heap, killed by the force of your sonic wall.
$n's sonic wall slams into you, causing your death.
$n's sonic wall slams into $N, causing $S death.
Your sonic wall narrowly misses its mark.
You watch with exhilaration as $n's sonic wall blasts past, missing you.
$N watches with exhilaration as $n's sonic wall blasts past, missing $M.
Your sonic wall explodes into $N, deafening $M with the pain.
$n's sonic wall explodes into you, deafening you with the pain.
$n's sonic wall explodes into $N, deafening $M with the pain.
$N simply shakes $S head at your pathetic attempt to harm $M.
$n seems to have decided that you should bitchslap $m.
$N shakes $S head at $n's pathetic attempt to him $N.

* Ray of Light
M
 93
Your holy ray of light explodes into $N's body, killing $M!
$n's holy ray of light explodes into your body, killing you!
$n's holy ray of light explodes into $N's body, killing $M!
You conjure a ray of light against $N, however it has no effect!
$n conjures a ray of light against you, however it has no effect!
$n conjures a ray of light against $N, however it has no effect!
Your ray of light exlpodes into $N's body!
$n's ray of light explodes into your body!
$n's ray of light explodes into $N's body!
Don't be a moron.
$n just tried to hurt you with a spell - holy mace - bitchslap?
$n is a moron. A big, fat moron.

* Fire Breath
M
 96
$N is killed by fire breath.
You are burned to ash, as $n breathes on you.
$n makes $N to ash.
$N is missed by fire breath.
$n breathes fire at you, but you avoids it.
$N avoids $n's firebreath.
$N is hit by fire breath.
$n burns you.
$N is partly made ash, as $n breaths fire.
$N, being immortal, is just warmed.
$n warms you.
$n warms $N.

* Gas Breath
M
 97
$N is killed by gas breath.
You die from the gas $n breathes on you.
$n kills $N with a gas breath.
$N is missed by gas breath.
$n breathes gas at you, but it has no effect.
$N avoids $n's gas.
$N is hit by gas breath.
$n gasses you.
$N is gassed by $n.
$N is immortal, so can't be gassed.
$n wants to gas you, but can't.
$n tries to gas $N, but can't.

* Frost Breath
M
 98
$N is killed by frost breath.
You are frozen to ice, as $n breathes on you.
$n makes $N to ice.
$N is missed by frost breath.
$n breathes frost at you, but you avoid it.
$N avoids $n's frost breath.
$N is hit by frost breath.
$n freezes you with $s breath.
$N is partly made ice, as $n breathes frost.
$N is immortal, and thus avoids your frost breath.
$n supplies you with air conditioning.
$n supplies $N with air conditioning.

* Acid Breath
M
 99
$N is killed by your acid breath.
You are corroded to nothing, as $n breathes on you.
$n corrodes $N to nothing.
$N is missed by acid.
$n breathes acid at you, but you avoids it.
$N avoids $n's acidbreath.
$N is hit by acid.
$n corrodes you.
$N is corroded as $n breaths acid.
$N is immortal, and thus is immune to acid.
$n helps you clean your hands with a little acid.
$n helps $N cleaning.

* Lightning Breath
M
 100
$N is killed by your lightning breath.
You are killed by $n's lightning breath.
$n killes $N with a lightning breath.
$N is missed by your lightning breath.
$n breathes lightning at you, but you avoids it.
$N avoids $n's lightning breath.
$N is hit by your lightning breath.
$n hits you with a lightning breath.
$N is hit by $n's lightning breath.
$N is immortal and immune to lightning breath.
$n tries to breath lightning upon you.
$n tries to breath lightning upon $N.

* HAIL OF STONE
M
 102
You drop a hail of stones ob $N's head, killing $M!
A hail of stones drops on your head, killing you.
A hail of stones drops on $N's head, killing $M.
Your hail of stones drop from the sky, but miss $N.
A hail of stones goes flying past you, much to $n's annoyance.
A hail of stones goes flying past $N, missing $M by inches.
You drop a hail of stones on $N!
A hail of stones pummel you from all directions.
A hail of stones pummels $N from all directions.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n! 

* FLYING FIST
M
 103
A flying fist of pure energy slams into $N, killing $M on impact!
A flying fist of pure energy slams into you, killing you on impact!
A flying fist of pure energy slams into $N, killing $M!
Your conjured fist of pure energy sails past $N, missing $M.
$n's conjured fist of pure energy sails past you, missing.
$n's conjured fist of pure energy sails past $N, missing $M.
A flying fist of pure energy slams into $N
A flying fist of pure energy slams into you.
A flying fist of pure energy slams into $N.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n! 

* SHOCK SPHERE
M
 104
You throw the glowing sphere at $N, killing $M dead.
$n throws a glowing sphere at you, killing you dead.
$n throws a glowing sphere at $N, killing $M dead.
You throw the glowing sphere at $N, but miss.
$n throws a glowing sphere at you, but misses.
$n throws a glowing sphere at $N, but misses.
You conjure a glowing sphere of pain and throw it at $N, hitting $M.
$n conjures a glowing sphere and hurtles it directly at you!
$n conjures a glowing sphere and hurtles it directlt at $N!
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n! 

* CAUSTIC RAIN
M
 105
A shower of boiling rain showers down on $N, Killing $M!
You are killed by a shower of awful, boiling rain.
$N is killed by a shower of awful, boiling rain.
You attempt to conjure boiling rain from the sky, but fail.
$n fails in $s attempt at a spell.
$n fails in $s attempt at a spell.
A shower of boiling rain showers down on $N.
A shower of boiling rain showers down on you.
A shower of boiling rain showers down on $N.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n! 

* WITHER
M
 106
You point a finger at $N, and $S skin withers and peels, leaving a dead husk.
$n points $s finger at you, causing your skin to wither and peel, killing you.
$n points $s finger at $N, causing $S skin to wither and peel, killing $M.
You attempt to wither $N, but fail.
$n points $s finger at you, uttering magical words, but nothing happens.
$n points $s finger at $N, uttering magical words, but nothing happens.
You point a finger at $N, withering $S skin on its bones.
$n points a finger at you, withering your skin on its bones.
$n points a finger at $N, withering $S skin on its bones.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* METEOR SWARM
M
 107
A swarm of meteors falls from the sky, killing $N.
A swarm of meteors falls from the sky, killing you!
A swarm of meteors falls from the sky, killing $N.
The meteor swarm rushes past $N, missing $M by inches.
A meteor swarm rushes past you, missing you by inches.
A meteor swarm rushes past $N, missing $M by inches.
The meteor swarm slams full force into $N's body!
A meteor swarm slams full force into your body!
A meteor swarm slams full force into $N's body!
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* BALEFIRE
M
 108
$N is engulfed in the arcane flames which you have called forth. $E is dead.
You are engulfed in the arcane flames which $n has called forth. You are dead.
$N is engulfed in the arcane flames which $n has called forth. $E is dead.
You attempt to summon the flames of the arcane, but fail.
$n attempts a complex spell, but nothing happens.
$n attempts a complex spell, but nothing happens.
$N is engulfed in arcane flames!
You are engulfed in arcane flames!
$N is engulfed in arcane flames!
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* SCORCH
M
 109
$N gets scorched by your magical fire so badly the $E dies.
$n engulfs you in magical fire that burns the skin from your bones, killing you.
$n engulfs $N in magical fire which burns $N to death.
The forces that be do not heed your call for $N's destruction.
$n calls forth the forces of the arcane, but they do not heed $s call.
$n calls forth the forces of the arcane, but they do not heed $s call.
$N get scorched by your magical flame.
You get scorched by $n's magical flame!
$N gets scorched by $n's magical flame.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* IMMOLATE
M
 110
Your spell slams into $N, killing $M instantly.
$n's spell slams into you with astounding force, killing you instantly.
$n's spell slams into $N with astounding force, killing $M instantly.
$N stands smirking at you as your spell goes wide.
You stand smirking at $n as $s spell goes wide.
$N stands smirking at $n as $n's spell goes wide.
You immolate $N with your powerful magic!
$n immolates you with $s powerful magic!
$n immolate $N with $s powerful magic!
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* HELLFIRE
M
 111
The fires of hell slam into $N, killing $M.
The fires of hell slam into you, killing you.
The fires of hell slam into $N, killing $M.
Your call to the underworld goes unheard.
$n weaves a strange incantation, but fails in $s casting.
$n weaves a strange incantation, but fails in $s casting.
You conjure the very fires of hell to strike $N!
$N conjures the very fires of hell, directing their full fire upon you.
$N conjures the very fires of hell, directing their full fire upon $n.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* FROSTBLADE
M
 112
A glowing blade of frost smites $N, killing $M instantly.
A glowing blade of frost smites you, killing you instantly.
A glowing blade of frost smites $N, killing $M instantly.
Your attempt at summoning the Frost Blade fails.
$n attempts to cast a spell your way, but fails.
$n attempts to cast a spell $N's way, but fails.
A blade of frost appears at your call, smiting $N with awesome force.
A blade of frost appears at $n's call, smiting you with awesome force.
A blade of frost appears at $n's call, smiting $N with awesome force.
Even if you could summon the blade, $N would kick your ass with it.
Goosebumps run deliciously up your arm as $n tries to cast a spell.
Was $n actually trying to cast a spell on $N? Nahhh - no way.

* FLAMEBLADE
M
 113
A glowing blade of flame smites $N, killing $M instantly.
A glowing blade of flame smites you, killing you instantly.
A glowing blade of flame smites $N, killing $M instantly.
Your attempt at summoning the Flame Blade fails.
$n attempts to cast a spell your way, but fails.
$n attempts to cast a spell $N's way, but fails.
A blade of flame appears at your call, smiting $N with awesome force.
A blade of flame appears at $n's call, smiting you with awesome force.
A blade of flame appears at $n's call, smiting $N with awesome force.
Even if you could summon the blade, $N would kick your ass with it.
You get a very warm, comforting feeling as $n tries to cast a spell.
Was $n actually trying to cast a spell on $N? Nahhh - no way.

* ACID STREAM
M
 114
A stream of acid pours from your outstretched hand, killing $N.
A stream of acid pours from $n's outstretched hand, killing you.
A stream of acid pours from $n's outstretched hand, killing $N.
Your stream of acid pours past $N, missing $M entirely.
A stream of acid from $n's hand pours past you, missing you completely.
A stream of acid from $n's hand pours past $N, missing $M completely.
A stream of acid pours from your hand, slamming into $N with melting force.
A stream of acid pours from $n's hand, slamming into you, melting your skin.
A stream of acid pours from $N's hand, melting $S skin.
Umm... $n is a God - acid don't hurt $m.
$n looks at you, concentrating. $e sort of looks like $e has to go to the bathroom.
Was $n actually trying to cast a spell on $N? Nahhh - no way.

* FLAME STRIKE
M
 115
You strike $N with a sheet of flaming death, killing $M.
$n strikes you with a sheet of flaming death, killing you.
$n strikes $N with a sheet of flaming death, killing $M.
The sheet of flames rushes past $N, barely even getting $M warm.
A sheet of flames rushes past you, missing you by a good margin.
A sheet of flames roars past $N, missing $M competely.
You strike $N with a sheet of flames.
$n strikes you with a sheet of flames.
$n strikes $N with a sheet of flames.
You - can't - hurt - a - God! Moron....
$n gets it in $s head that $e might be able to hurt you. Ha!
$n looks a bit disturbed that $s spell won't work on $N.

* FINGER OF DEATH
M
 116
You point a wicked finger $N's way, causing $S death.
$n points a wicked finger your way, stopping your heart completely.
$n points a wicked finger $N's way, causing $N's heart to stop.
You point your finger at $N with no effect.
$n points $s finger at you, but nothing happens.
$n points $s finger at $N, but nothing happens.
You point a wicked finger $N's way, causing $M serious damage.
$n points a wicked finger your way, causing you serious damage.
$n points a wicked finger in $N's direction as $N begins to cry in agony.
You point at $N. Nothing happens.
$n points at you. You must be the one.
$n points at $N. Yep, that's $N, all right.

* SCOURGE
M
 117
A deafening surge of demons come to your call, rending $N's soul to shreds.
A deafening surge of demons come to $n's call, rending your soul in two.
A deafening surge of demons come to $n's call, rending $N limb from limb.
You try to call the Scourge to your command, but it does not reply.
$n raises $s arms in a dramtic posture... nothing happens.
$n raises $s arms in a dramtic posture... nothing happens.
You call the Scourge to your bidding, attacking $N.
$n calls the Scourge to $s bidding, attacking you.
$n calls the Scourge to $s bidding, attacking $N.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* SOUL RIP
M
 118
You reach into $N's soul, tearing out the last vestiges of life.
$n reaches into your soul, tearing out the last vestiges of life.
$n reaches into $N's soul, tearing out the last vestiges of life.
$N's life force is too strong, you cannot reach $S soul.
$n tries to rip your soul from your body, but fails.
$n attempts to tear $N's soul from $S body, but fails.
You rip shreds of $N's soul from $M, leaving $M writhing in pain.
$n rips shreds of your soul from you, leaving you writhing in pain.
$n rips shreds of $N's soul from $M, leaving $M writhing in pain.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* FELLBLADE
M
 119
A hazy blade of black appears in your hand, guiding a killing stroke on $N.
A hazy blade of blackness appears in $n's hand, guiding a killing stroke upon you.
A hazy blade of black appears in $n's hand, guiding a killing stroke on $N.
You swing the Fellblade, but miss $N.
$n conjures the Fellblade, but misses you with $s swing.
$n conjures the Fellblade, but misses $N with $s swing.
You conjure the Fellblade, slicing $N with its evil power.
$n conjures the Fellblade, slicing you with its evil power.
$n conjures the Fellblade, slicing $N with its evil power.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* EXTERMINATE
M
 120
You call to the minions of evil and they answer, tearing $N to pieces.
$n calls the minions of evil to his aid and they answer, tearing you to pieces.
$n calls the minions of evil to his aid and they answer - tearing $N to pieces.
You call to the minions of evil but they do not respond.
$n makes a strange cry to the Underworld, but it goes unanswered.
$n makes a strange cry to the Underworld, but it goes unanswered.
The minions of evil come to your bidding, attacking $N.
The minions of evil come to $n's bidding, attacking you.
The minions of evil come to $n's bidding, attacking $N.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* BLADES OF LIGHT
M
 122
Twin blades of pure light slice $N clean in two.
Twin blades of pure light slice you clean in two.
Twin blades of pure light slice $N clean in two.
You raise your voice in incantation, but your spell goes wrong.
$n raises $s voice in incantation, but nothing happens.
$n raises $s voice in incantation, but nothing happens.
Twin blades come into being, attacking $N with deadly precision.
Twin blades come into being, attacking you with deadly precision.
Twin blades come into being, attacking $N with deadly precision.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* FLAMES OF PURITY
M
 123
Cascading flames rain down from the heavens, washing over $N, killing $M.
Cascading flames rain down from the heavens, killing you.
Cascading flames rain down from the heavens, killing $N.
Your call for the purifying flames goes unheard.
$n attempts a complex spell, but fails.
$n attempts a complex spell, but fails.
Purifying flames wash over $N, causing serious damage.
Purifying flames wash over you, causing serious damage.
Purifying flames wash over $N, causing serious damage.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* PRISMATIC BEAM
M
 124
A beam of multicolored light flies from your raised hand, killing $N.
A beam of multicolored light flies from $n's raised hand, killing you.
A beam of multicolored light flies from $n's raised hand, killing $N.
Your beam of many lights flies past $N without making contact.
A beam of many colors is flung from $n's hand, flying past you without harm.
A beam of many colors is flung from $n's hand, flying past $N without harm.
Your prismatic beam lands with full impact on $N!
$n's prismatic beam lands with full impact on you!
$n's prismatic beam lands with full impact on $N!
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* HOLOCAUST
M
 126
You call a holocaust to your bidding, killing $N in it!
$n calls a holocaust to $s bidding, killing you in it!
$n calls a holocaust to $S bidding, killing $N in it!
Your call for a holocaust goes unheard.
$n calls in a mighty voice for a holocaust, but nothing happens.
$n calls in a mighty voice for a holocaust, but nothing happens.
You envelop $N in a mighty holocaust, inflicting great damage.
$n envelopes you in a mighty holocaust, inflicting great damage.
$n envelopes $N in a mighty holocaust, inflicting great damage.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

* CRY FOR JUSTICE
M
 127
Your cry for Justice is heard and answered. $N has been slain.
$n makes a desperate cry for Justice, a powerful force slaying you where you stand.
$n's desperate cry for Justice is heard and answered. $N has been slain.
You make a deperate cry for Justice, your words echoing emptily.
$n makes a deperate cry for Justice, $s words echoing emptily.
$n makes a deperate cry for Justice, $s words echoing emptily.
Your cry for Justice is answered - $N is slammed with astonishing force.
$n's cry for Justice is answered - you are slammed with astonishing force.
$n's cry for Justice is answered - $N is slammed with astonishing force.
Get real.  You can't hurt $n. $e's a god!
$N, the fool, tried to hurt you!
$N, the fool, tried to hurt $n!

$
