* Dibrova-style messages file.  The structure is identical to
* CircleMUD 3.0, with the difference being that we keep 
* separate lists for various messages.  Each list is loaded
* from it's own file.
*
* Messages for weapons and NPC hits.

***************************************************************************
*                           Weapon Attacks                                *
***************************************************************************

* Hit
M
 1
/cCYou punch $N's head with a blow that crushes $S skull!/c0
/cR$n punches your head with a blow that crushes your skull!/c0
/cr$n punches $N's head so hard that $S skull cracks open!/c0
/cYYou swing your fist at $N, but miss $M!/c0
/cWYou barely avoid $n's fist as $e takes a swing at you!/c0
/cw$N barely avoids a blow from $n!/c0
#
#
#
Your fist flops as your body refuses to fight the mighty $N.
$n seems to be having trouble getting $s body to fight you!!
$n's body rebels against $m when $e tries to punch $N.
M
 1
/cCYou punch $N in $S kidneys resulting in $S immediate death!/c0
/cRYou recieve a punch in your kidneys which ends your worldly misery -- R.I.P.!/c0
/cr$n punches $N in the kidneys causing immediate death!/c0
/cYYou wildly punch at the air, missing $N./c0
/cW$n misses a wild punch at you./c0
/cw$n practices shadow-boxing while $N takes a break./c0
#
#
#
Instead of letting you punch $M, $N forces you to play Punch and Judy!!!
You convince $n of playing Punch and Judy instead of punching you.
$N convinces $n that no punching is necessary.
M
 1
/cCYou hit $N with such force that $S neck snaps in two!/c0
/cR$n hits you with such force that your neck snaps in two!/c0
/cr$N's neck is snapped in two by a powerful blow from $n!/c0
/cYYou try to hit $N who easily avoids the blow./c0
/cW$n tries to hit you but you easily avoid the blow./c0
/cw$n tries to hit $N who easily avoids the blow./c0
#
#
#
You try to hit $N but hit yourself instead!
$n tries to hit you but you hits $mself instead!
$n tries to hit $N but hits $mself instead!
M
 1
/cCYou hit $N with a blow that breaks $S spine!/c0
/cR$n hits you with a blow that breaks your spine!/c0
/cr$n hits $N with a blow that breaks $S spine!/c0
/cY$N ducks under your fist as you try to hit $M./c0
/cWYou duck under $n's fist as $e takes a swing at you./c0
/cw$N ducks under $n's fist as $e takes a swing at $M./c0
#
#
#
It isn't polite to swing at a GOD!
$n tries to take a swing at you -- how pathetic!
$n pathetically tries to take a swing at $N - ha!

* Sting
M
 2
/cCYou drive a sting directly into the heart of $N, killing $M!/c0
/cRWith a powerful driving force, $n's sting tears right through your chest causing instant death!/c0
/cr$n drives $s sting through $N's chest, killing $M!/c0
/cYYou miss $N with your stinging blow!/c0
/cW$n drives $s stinging blow at you, barely missing!/c0
/cwYou watch in fright as $n stings at $N, missing by mere inches!/c0
#
#
#
Sting -- God... What are you thinking?
$n tries to sting you, somewhat comical to tell the truth.
$n stings at $N, then looks horrified as $N grins at $m!
M
 2
/cCYou violently sting $N repeatedly, causing $S death!/c0
/cRYou die a horrid death as $n stings you repeatedly all over your body!/c0
/crAs $n stings $N all over the place, $N falls lifeless to the ground./c0
/cYYou sting towards $N, but miss $M!/c0
/cW$n misses you with $s sting!/c0
/cwYou watch on as $n stings at $N, but misses!/c0
#
#
#
You sting at $N, and all that happens is that $E slaps himself as if a mosquito bit $M.
Was that a bee you just felt?  Oh.. wait, it was just $n.
$N begins to slap at $Mself as $n tries to sting $M.

* Whip
M
 3
/cCYou whip $N's head right off of $S body!/c0
/cR$n whips your head right off of your body!/c0
/cr$n whips $N's head right off of $S body!/c0
/cYYou crack your whip at $N but it hits you in the face!/c0
/cW$n cracks $s whip at you and it hits $m in the face!/c0
/cw$n cracks $s whip at $N but only hits $mself in the face!/c0
#
#
#
You'd better stop before $N whips your butt.
Pathetic little $n is trying to whip you... how cute.
$n tries to whip $N - isn't he cute?
M
 3
/cCYour dextrous whip messily tears $N's torso right off!/c0
/cR$n's whip messily tears you right in half!/c0
/crWith an evil grin, $n messily whips $N in half!/c0
/cYYou try to whip $N but whip the ground instead!/c0
/cW$n tries to whip you but whips the ground instead!/c0
/cw$n tries to whip $N but whips the ground instead!/c0
#
#
#
Don't try to whip $N.
$n is trying to whip you.  Yawn.
$n tries to whip $N - yawn.

* Slash
M
 4
/cCYou beautifully slash $N into two parts -- both dead./c0
/cRYour upper body is disconnected from your legs as $n slashes at you -- R.I.P.!/c0
/cr$N is slashed in two by a masterful stroke of $n!/c0
/cYYour desperate slash at $N is easily avoided by $M./c0
/cWYou easily avoid a slash from $n./c0
/cw$N nimbly avoids $n's slash./c0
#
#
#
Your cunning slash at $N is fruitless.
You nimbly stop a slash from $n.
$N stops a cunning slash from $n who looks disappointed.
M
 4
/cCYour slash at $N results in a pool of blood and $S immediate death!/c0
/cRBlood spurts all over as $n slashes at you.  You die.../c0
/cr$n slashes at $N who colors everything red with blood from $S lethal wound./c0
/cYYou miss $N by an inch, curse that brat!/c0
/cWYou manage to dodge $n's slash and laugh, HA!/c0
/cw$n's slash misses $N who laughs in sheer delight, HA!/c0
#
#
#
Come on, what makes you think you can slash at a GOD?!
You barely register the puny creature before you...
The great $N seems to ignore $n's slashes.
M
 4
/cC$N cries out in agony as you slash $S ribcage open!/c0
/cRYour ribcage is slashed open by $n -- R.I.P.!/c0
/cr$n nicely dissects $N's ribcage with a single slash!/c0
/cYYou try to slash $N but miss by a mile./c0
/cW$n's slash misses you by a mile./c0
/cw$n's slash at $N misses $M by a mile./c0
#
#
#
It's rude to try to slash a GOD, you know.
$n tries to slash you -- how rude!
$n tries to slash $N -- how rude!
M
 4
/cCYour powerful slash cleanly cuts off $N's head, which rolls away with a look of horror on it./c0
/cRYou briefly feel the sensation of flight as $n slices your head cleanly off!/c0
/cr$n cleanly slices off $N's head which rolls away with a look of horror on it!/c0
/cY$N is cooled by the breeze of your missed slash at $M./c0
/cW$n cools you with the breeze of $s missed slash at you./c0
/cw$n cools $N with the breeze of $s missed slash./c0
#
#
#
Yeah, right.
$n tries to slash you... yeah, right.
$n tries to slash $N... yeah, right.

* Bite
M
 5
/cCYou sink your teeth deep into $N's neck -- blood sprays everywhere!/c0
/cR$n sinks $s teeth deep into your neck, tearing your jugular vein to bits!/c0
/cr$n sinks $s teeth deep into $N's neck, tearing $S jugular vein to bits!/c0
/cYYou snap your teeth at $N but miss him./c0
/cW$n snaps $s teeth at you fiercly but misses./c0
/cw$n fiercly snaps $s teeth at $N but misses the mark./c0
#
#
#
You attempt to bite $N.  Ouch!  That hurt!
$n tries to bite you, how funny.
$n tries to bite $N - funny, huh?
M
 5
/cCYou bite $N through $S ribcage and into $S heart -- $e falls to the ground in agony./c0
/cR$n bites you right your ribcage and into your heart -- you fall to the ground writhing in agony.../c0
/cr$n's powerful jaw bites through $N's ribcage into $S heart -- $E falls to the ground writhing in agony!/c0
/cYYou try to bite $N but bite your tongue instead!/c0
/cW$n tries to bite you but bites $s tongue instead!/c0
/cw$n tries to bite $N but bites $s own tongue instead!/c0
#
#
#
Aren't you trying to bite off more than you can chew?
$n snaps at you but realizes $e is biting off more than $e can chew.
$n stupidly tries to bite off more than $e can chew by snapping at $N.

* Bludgeon
M
 6
/cCYou forcefully bludgeon $N whose head suddenly cracks open like a walnut!/c0
/cR$n bludgeons your head which cracks open like a walnut!/c0
/cr$n ruthlessly bludgeons $N whose head cracks open like a walnut!/c0
/cYYou fruitlessly try to bludgeon $N./c0
/cWYou easily dodge $n's attempt to bludgeon you./c0
/cw$n tries to bludgeon $N who easily avoids the blow./c0
#
#
#
Your attempt to bludgeon $N fails, luckily for you $N has a good sense of humor!
Your patience is tried when $n tries to clobber you.
$N restrains $Mself from zapping $n when $e attempts to bludgeon the mighty one.
M
 6
/cCYour relentless bludgeoning of $N finally results in $S broken neck!/c0
/cR$n's relentless bludgeoning of you finally results in your broken neck!/c0
/cr$n's relentless bludgeoning of $N finally results in $N's broken neck!/c0
/cYYou try to bludgeon $N who simply laughs at you./c0
/cW$n tries to bludgeon you, but you avoid $m and laugh./c0
/cw$N laughs at $n's attempt to bludgeon $M./c0
#
#
#
Your attempt to bludgeon $N fails, luckily for you $N has a good sense of humor!
Your patience is tried when $n tries to clobber you.
$N restrains $Mself from zapping $n when $e attempts to bludgeon the mighty one.

* Crush
M
 7
/cCYou crush $N right out of existence!/c0
/cR$n crushes you right out of existence!/c0
/cr$n crushes $N right out of existence!/c0
/cYYou try to crush $N who jumps out of the way!/c0
/cW$n tries to crush you but you jump out of the way!/c0
/cw$n tries to crush $N who jumps out of the way!/c0
#
#
#
A pox on thee and thy pitiful crush on $N!
$n seems to have a crush on you...
$n seems to have a crush on $N...
M
 7
/cCYou crush $N's entire body, making a terrible mess!/c0
/cR$n crushes your entire body, making a terrible mess!/c0
/cr$n crushes $N's entire body, making a terrible mess!/c0
/cYYou hopelessly try to crush $N./c0
/cW$n hopelessly tries to crush you./c0
/cw$n hopelessly tries to crush $N./c0
#
#
#
A pox on thee and thy pitiful crush on $N!
$n seems to have a crush on you...
$n seems to have a crush on $N...

* Pound
M
 8
/cCYou pound $N right into the ground!/c0
/cR$n pounds you six feet under./c0
/cr$n pounds $N mightily on the head, crushing $S entire body!/c0
/cYYou pound at the air as $N nimbly steps out of the way!/c0
/cWYou jump out of the way in a panic as $n pounds at you!/c0
/cw$n looks perturbed as $s pound misses $N!/c0
#
#
#
You pound $N!  And $E thanks you for it?  *boggle*
$n gives you a pound.  Wonder what the exchange rate is...
$n starts giving pounds to $N who begins to count the money.
M
 8
/cCYou pound on $N with reckless abandon when you realize that $E is dead./c0
/cRWith $s reckless pounding attacks, you succomb to death./c0
/cr$N falls under $n's pounding blows, yet $n continues $s attack!/c0
/cYYou hear the air whistle as you split the air with your pound!/c0
/cW$n pounds in your direction, causing a whistling sound!/c0
/cwWith a loud whistle through the air, $n misses $s pounding attack upon $N!/c0
#
#
#
Who are you trying to kid?
Hmmm... I think you missed the joke that $n was trying to tell you.
$N looks somewhat perplexed as $n tries to pound him!

* Claw
M
 9
/cCYou claw $N's face right off!/c0
/cR$n claws your face right off!/c0
/cr$n claws $N's face right off!/c0
/cYYou try to claw at $N but miss!/c0
/cW$n tries to claw at you but misses by a hair!/c0
/cw$n tries to claw at $N, missing by a hair!/c0
#
#
#
You dummy!  Not the claw, the claw!/c0
$n must be crazy - trying to claw at you!/c0
$n must be crazy - trying to claw at $N!/c0
M
 9
/cCYour razor-sharp claws rip $N wide open!/c0
/cR$n's razor-sharp claws rip you wide open!/c0
/cr$n's razor-sharp claws rip $N wide open!/c0
/cYYou try to claw at $N but almost nick yourself instead!/c0
/cW$n tries to claw at you but nearly nicks $mself instead!/c0
/cw$n tries to claw at $N but nearly nicks $mself instead!/c0
#
#
#
You dummy!  Not the claw, the claw!
$n must be crazy - trying to claw at you!
$n must be crazy - trying to claw at $N!

* Maul
M
 10
/cCYou maul $N across the chest and $E screams in pain as $E falls lifeless to the ground./c0
/cRAs $n mauls you in the chest, you feel a searing pain... then nothing./c0
/crWith a brutal maul to the chest, $N slaughters $n!/c0
/cYYou swing wildly with your maul, almost hitting yourself!/c0
/cWPhew!  $n missed you with $s wild maul!/c0
/cw$n mauls at $N, missing wildly!/c0
#
#
#
Mauling a God?  What would your poor mother think?  Of course, you probably wouldn't hesitate to maul her too.
$n tries to maul you, and as $e fails, looks quite horrified.  How pleasant.
$N laughs as $n tries to maul $M.  How comical.

* Thrash
M
 11
/cCYou bring $N within the thrashing of $S life, and then thrash $M one last time, killing $M./c0
/cR$n thrashes you violently, and you die./c0
/crWith a horrible thrashing, $N falls lifeless under $n's blows!/c0
/cYYou miss your thrash against $N!/c0
/cWWhat a stroke of luck, $n seems to have missed you with $s thrash!/c0
/cw$n thrashes madly at $N, missing $m!/c0
#
#
#
Thrash a God?  More likely that $N would thrash you, don't you think?
What a fool, $n tried to thrash you.  *sigh*
Looking rather silly, $n tries to thrash at $N.

* Pierce
M
 12
/cCYou succesfully pierce $N and $S dead body falls to the ground in a lifeless heap./c0
/cR$n pierces you.  You are no longer a living member of this world -- R.I.P.!/c0
/cr$n pierces $N whose suddenly lifeless body falls to the ground!/c0
/cYYou try to pierce $N but pierce the air instead!/c0
/cW$n pierces holes in the air./c0
/cw$n tries to pierce air instead of fighting $N./c0
#
#
#
The mighty $N begins to think you a nuisance!!!
Your patience is almost gone when you stare back at $n.
The air is loaded when $N angrily wards off a piercing attack from $n.
M
 12
/cCYou pierce $N's heart, you heartbreaker you.../c0
/cR$n breaks your heart, goodbye cruel world.../c0
/cr$n pierces the heart of $N who falls to the ground clutching at the wound!/c0
/cYYou lunge at $N without managing to pierce $M./c0
/cW$n tries to pierce you but fails miserably./c0
/cw$n lunges at $N but can't pierce $M./c0
#
#
#
The great $N sends you a piercing look, OOPS!
You return $n's pierce with a piercing look, hmmm...
$N returns $n's pierce with a piercing look, hmmm...

* Blast
M
 13
/cCYou blast $N with all of your might, killing $M!/c0
/cRWith $s powerful blast, $n tears your life from your body!/c0
/cr$N falls lifeless as $n's blast rips $M apart!/c0
/cYYou blast wildly, missing $N by a mere inch or two!/c0
/cWYou skillfully avoid $n's wild blast!/c0
/cw$n misses $N with $s wild blast!  What luck $N seems to have!/c0
#
#
#
Are you kidding?  What do you expect your feeble blast to do to $N?/c0
Heh.  $n tried to blast you.  Good thing you have blastproof armour./c0
$n looks afraid of the consequences as $e tries fruitlessly to blast $N./c0

* Punch
M
 14
/cCYou punch at $N causing $S face to collapse under the blow, blood everywhere.  Doesn't look like $N will recover.  Ever./c0
/cR$n's forceful punch causes you to see red, until you die shortly thereafter./c0
/cr$n punches $N right in the face!  There is blood everywhere, and $N seems to be dead!/c0
/cYYou miss $N with your haymaker!/c0
/cW$n throws a haymaker at you which whistles by your ear!/c0
/cw$n just misses $N with a strong punch!/c0
#
#
#
Punch a God?  May be smarter to punch a wall for a bit.  You might do more damage to it.
Is that a quiet whistling noise you hear as $n is swinging $s fist about?
$n looks like $e would prefer to have punched a wall rather than trying to punch $N.

* Stab
M
 15
/cCYou stab $N through the heart!  Instant death!/c0
/cR$n drives a stab at you, it pierces your heart!  RIP!/c0
/cr$n stabs brutally at $N, killing him as $N is impaled by $n!/c0
/cYYou stab at $N, missing!/c0
/cW$n misses a particularily nasty stab in your direction!/c0
/cw$n stabs at $N!  $e misses!/c0
#
#
#
You stab at $N!  Too bad $E's a god, huh?
$n stabs at you!  Lucky for you that you are immune to this kind of thing.
You watch in pity as $n stabs towards $N missing in the most futile way possible!
M
 15
/cCYou stab forth towards $N, hitting $M in the abdomen causing a messy but mortal wound!/c0
/cR$n stabs you in the stomach, and you watch your insides fall out as you die./c0
/crMaking a mess of $N, $n kills $M with a stab to the midsection./c0
/cYYou stab at $N, barely missing $M!/c0
/cW$n stabs at you, missing by a good mile or so!/c0
/cw$N grins at $n as the stab sent by $n goes wide!/c0
#
#
#
Gods can't be stabbed, did noone ever teach you that?  And $N just so happens to be one.
It sure is nice being a god isn't it... especially since $n can't hit you with $s stabs.
$n stabs at $N only to discover $N's immunity to stabbing weapons.

* Spell
M
 16
/cCYour spell causes $N's body to desintegrate into a mass of molten goo./c0
/cR$n's spell hits you dead on, causing a very messy and untimely death for you./c0
/cr$n has killed $N with his deadly spell!/c0
/cYYou attempt to cast a deadly spell at $N, but narrowly miss./c0
/cW$n casts a deadly spell your way, but it goes wide and strikes behind you with a loud /cpBOOM!/c0
/cw$n casts a deadly spell at $N, but $E manages to avoid it./c0
/cCYour spell hits $N dead on in the chest, causing serious damage./c0
/cR$n hits you in the chest with a deadly spell, causing you to stagger a bit./c0
/cr$N is hit square in the chest by a deadly spell sent from $n!/c0
Give it up, puny mortal, you'll only hurt yourself.  $N smirks at you.
Now that's balls!  $n just tried to cast a spell on you!
Like a typically book-smart mage would, $n tries to cast a spell on $N.  Yeah.

* Embrace
M
 17
/cCYou reach out and Embrace $N, causing $s immediate death./c0
/cR$n reaches out and Embraces you their a deadly Embrace./c0
/cr$n has killed $N with their deadly Embrace!/c0
/cYYou reach out and try to Embrace $N, but $N nimbly steps outside your grasp./c0
/cW$n tries to Embrace you in their deadly embrace, but you are able to avoid them./c0
/cw$n tries to Embrace $N, but $E is able to avoid it./c0
/cCYou Embrace $N, holding them close in your arms, sucking out their life./c0
/cR$n wraps you in a cold Embrace, sucking your life from you./c0
/cr$n wraps $N in a chilling Embrace, and begins to suck the life from $m!/c0
What kind of a jackass tries to Embrace a god, anyway?
Hey, it looks like $n might like you a little... $e just tried to Embrace you!
$n attempts to embrace $N.  Hmmm, they always said $n didn't have much upstairs...

* Jab
M
 18
/cCYou lunge at $N, jabbing $M through the heart - killing $M!/c0
/cR$n lunges at you, jabbing you through the heart!./c0
/cR$n lunges at $N, jabbing $M through the heart!./c0
/cYYou jab at $N, but miss./c0
/cW$n jabs at you, but misses./c0
/cw$n jabs at $N, but misses./c0
/cCYou lunge at $N, jabbing $M good!/c0
/cC$n lunges at you, jabbing you with $s weapon!/c0
/cC$n lunges at $N, jabbing $M good!/c0
You cannot jab a god, no matter how hard you try - stupid.
$n just tried to hurt you. Maybe you should... hurt back?
$n is an idiot.

* Cleave
M
 19
/cCYou cleave through $N's skull!/c0
/cC$n cleaves through your skull!/c0
/cC$n cleaves through $N's skull!/c0
/cYYou swing an over-handed blow at $N, but miss./c0
/cW$n swings an over-handed blow at you, but misses./c0
/cw$n swings an over-handed blow at $N, but misses./c0
/cCYour cleave leaves $N bleeding!/c0
/cC$n's cleave leaves you bleeding./c0
/cC$n's cleave leaves $N bleeding./c0
You cannot hurt a god, no matter how hard you try - stupid.
$n just tried to hurt you. Maybe you should... hurt back?
$n is an idiot.

* Suffering
M
 99
#
/cCYou feel wounded -- too wounded -- you die.../c0
/cR$N lies suffering on the ground until no blood is left in $S body./c0
#
suffer miss victim - should never see.
suffer miss room - should never see.
#
/cRYou lie on the ground suffering from your terrible wounds.../c0
/cr$N lies helplessly on the ground and suffers.../c0
#
Suffer god victim - should never see.
Suffer god room - should never see.
M
 99
#
/ccYou can only lie still as your last heartbeat ebbs.../c0
/cr$N suffers from bloodlack, and the lack of a beating heart.../c0
#
suffer miss victim - should never see.
suffer miss room - should never see.
#
/ccYou lie on the ground suffering from bleeding wounds.../c0
/cr$N lies immobile on the ground, suffering.../c0
#
Suffer god victim -- should never see.
Suffer god room -- should never see.

$
